[versions]
annotations = "26.0.2-1"
wisp = "1.0.1-SNAPSHOT"
jnats = "2.21.5"
lettuce = "6.8.1.RELEASE"
jackson = "2.20.0"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
wisp = { module = "io.github.wisp:wisp", version.ref = "wisp" }
jnats = { module = "io.nats:jnats", version.ref = "jnats" }
lettuce-core = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }